= How to install

Refined Storage is run using a modloader.
The supported modloaders are **NeoForge and Fabric**.

Installing Refined Storage is the same as for any other NeoForge or Fabric mod.

== Setting up NeoForge or Fabric

You'll need a working NeoForge or Fabric instance to use Refined Storage.
You can use launchers like MultiMC or even the vanilla launcher to do this.

== Downloading the mod

Download a Refined Storage `.jar` file for your Minecraft version and modloader from official sources:

- link:https://www.curseforge.com/minecraft/mc-mods/refined-storage[CurseForge]
- link:https://modrinth.com/mod/refined-storage[Modrinth]
- link:https://github.com/refinedmods/refinedstorage2/releases[GitHub]

== Installing the mod

Once you have the `.jar` file, place it in the `mods/` directory of your instance.
You may have to start up your instance at least once so the modloader can autogenerate the `mods/` directory.

=== Using the CurseForge App (and other launchers)

When you're using the CurseForge App (and most other launchers), you can install Refined Storage in an instance with one click, without having to copy over `.jar` files.

== Configuring the mod

Changing the configuration isn't needed in most cases.
However, you can change the configuration to suit your needs.
The configuration file is located in the `config/` directory of your instance.

- When using NeoForge: `config/refinedstorage-common.toml`
- When using Fabric: `config/refinedstorage.toml`

[#_optional_dependencies]
== Optional dependencies

Refined Storage can work perfectly by itself without any additional mods, but it's helpful to install a few other mods alongside it.

=== Integration with recipe viewers

These mods will help you view the recipes of the various items and blocks in the mod.

- xref:integrations/just-enough-items.adoc[]
- xref:integrations/roughly-enough-items.adoc[]
- xref:integrations/emi.adoc[]

=== Energy generation

Storage networks need energy to run.
You'll need a mod that can generate energy.

If you want to play with Refined Storage without requiring, customize your modpack and add recipes for the creative variants of the Refined Storage blocks and items.

=== Other integrations

- xref:integrations/mekanism.adoc[]
- xref:integrations/curios.adoc[]
- xref:integrations/trinkets.adoc[]
