= Grid
:icon: grid.png
:from: v0.3.0-alpha

The {doctitle} is a block that allows access to the resources stored in the storage network.

You can insert and extract resources in the storage network within the {doctitle}.

You can place the {doctitle} in any direction.

[#_basic_controls]
== Basic controls

[cols="1,1"]
|===
| Type | Description

| Left-clicking with an empty hand in the {doctitle} | Extracts the maximum stacking size of the resource.
| Left-clicking with a resource container (like a bucket) in hand in the {doctitle} | Fills the resource container.
| Right-clicking with an empty hand in the {doctitle} | Takes half of the maximum stacking size of a resource
| Left-clicking with a resource in hand in the {doctitle} | Inserts the resource into the {doctitle}.
| Right-clicking with a resource in hand in the {doctitle} | Inserts a single resource into the {doctitle}.
| Right-clicking with a resource container in hand in the {doctitle} | Empties the resource container into the {doctitle}.
| SHIFT clicking a resource in the player inventory | Inserts the resource into the {doctitle}.
| CTRL + clicking with an empty hand in the {doctitle} | Forces the autocrafting request window to open *even if the resource is available*.
| CTRL + X | Clears the crafting matrix in the xref:crafting-grid.adoc[] to the storage network.
| Right click on search bar | Clears the search query.
| Tab | Selects the search bar when the {doctitle} isn't in autoselected mode.
|===

=== Scrolling controls

[cols="1,1"]
|===
| Type | Description

| Scrolling up + SHIFT in the {doctitle} | Inserts a single resource into the {doctitle}.
| Scrolling down + SHIFT in the {doctitle} | Extracts a single resource from the {doctitle}.
| Scrolling down + CTRL in the {doctitle} | Extracts a resource from the {doctitle} on the player's hand.
| Scrolling up + SHIFT in the player inventory | Inserts a single resource into the {doctitle}.
| Scrolling down + SHIFT in the player inventory | Extracts a single resource from the {doctitle}.
|===

== Searching

Use the text box at the top of the {doctitle} to search.
You can just type words to search for resources with that name in your storage network.

However, the search is more powerful than that, supporting an entire query language with syntax highlighting.

- You may use logical operators like `&&` (AND) and `||` (OR) .
- You may use parentheses to group expressions.
- You may use following unary operators:
* `!` (NOT)
* Search by mod name with `@`
* Search in tooltips with `#`
* Search in tags with `$`
* `>`, `<`, `>=`, `<=` for amount comparisons

=== Autoselected mode

The {doctitle} can be configured to automatically select the search bar when opening it.

> The autoselected mode applies to all {doctitle}s and is stored on the client for each player.

=== Recipe viewer synchronization

The search box can be configured to synchronize with the recipe viewer search box, one-way (from the {doctitle} to the recipe viewer) or two-way synchronization.

Read more:

- xref:../integrations/just-enough-items.adoc[]
- xref:../integrations/roughly-enough-items.adoc[]
- xref:../integrations/emi.adoc[]

=== Remember search query

The {doctitle} can be configured to remember the search query when closing and re-opening the {doctitle}.
You can do this by modifying the `rememberSearchQuery` config option.

== Sorting

The resources in a {doctitle} can be sorted in a ascending or descending manner in various ways:

- By name
- By quantity
- By ID
- Last modified

> The sorting type applies to all {doctitle}s and is stored on the client for each player.

== Display

=== View type

The {doctitle} can be configured to only show autocraftable resources or only show non-autocraftable resources.

> The view type applies to all {doctitle}s and is stored on the client for each player.

=== Size

The size of any {doctitle} can be configured as well:

[cols="1,1"]
|===
| Type | Description

| Stretched | The {doctitle} will take up all the vertical screen space.
| Small | 3 rows
| Medium | 5 rows
| Large | 8 rows
| Extra large | 12 rows
|===

When choosing the stretched size, the {doctitle} will take up all the vertical screen space.
This can be limited through the `maxRowsStretch` config option.

> The size applies to all {doctitle}s and is stored on the client for each player.

=== Detailed tooltips

By default, the tooltips for resources in a {doctitle} are a little bit bigger to display the total amount and the last modified information.
This can be turned off by using the `detailedTooltip` config option.

=== Other configuration

By default, the {doctitle} uses a small font size to display resource amounts.
Use the `largeFont` config option to change this.

The scrollbar uses __smooth-scrolling__, if you prefer regular scrolling you can use the `smoothScrolling` config option.

== Prevent sorting while shift is down

By default, the {doctitle} doesn't sort when you are inserting and extracting resources from the network.
As soon as you stop pressing the SHIFT key, the view is sorted again.

To disable this behavior, modify the `preventSortingWhileShiftIsDown` config option.

include::../../partials/recoloring.adoc[]
