= Controller
:from: v0.3.0-alpha
:icon: controller.png

The {doctitle} is used to provide the storage network with energy.

At least one is required in each network in order for the network to be active.

You may add multiple {doctitle}s to meet the energy demands of your network.

== Generating energy

Since Refined Storage is a storage mod that is designed to be used in modpacks with other mods, there is no built-in way to generate energy. You are supposed to feed the {doctitle} with energy generated through another mod.

== Energy usage

- The energy is extracted per tick.
- The amount of energy that is extracted depends on the devices that are connected to the network. Other than the device type, more devices will consume more energy.

If the {doctitle} runs out of energy, the network will start extracting from another {doctitle} if available. If there is no other {doctitle} available, the network will stop working and become inactive.

When the {doctitle} is broken, it will maintain its energy.

include::../../partials/recoloring.adoc[]